"""Configuration with all available dive pool elements.

Supports external override file:
- file name: `DrawGenerators.cfg`
- location: current working directory
- created automatically with defaults when missing
- only uppercase variables override bundled defaults
"""

from __future__ import annotations

import runpy
from pathlib import Path
from pprint import pformat

# UI text configuration.
APP_TITLE_TEXT = "D2W & D4W"
DEFAULT_COMPETITION = "D2W_D4W"

# Shuffle animation configuration.
ANIMATION_STEP_DELAY_MS = 70
ANIMATION_STEP_COUNT = 50
ANIMATION_PREVIEW_ROUNDS = 5


COMPETITIONS = {
    "D2W_D4W": {
        "title": "D2W & D4W",
        "snakes": [
            ("S1", "Head-down Inface Snake"),
            ("S2", "Head-down Switching Snake"),
            ("S3", "Head-up Inface Snake"),
            ("S4", "Head-up Switching Snake"),
            ("S5", "Head-down Mixed Snake"),
            ("S6", "Head-up Mixed Snake"),
        ],
        "verticals": [
            ("V1", "Back Layout"),
            ("V2", "Butterfly"),
            ("V3", "Classic"),
            ("V4", "Head-down 360°"),
            ("V5", "Head-up 360°"),
            ("V6", "Crossing Classic"),
            ("V7", "Bottom Loop"),
            ("V8", "Crossing Layout"),
        ],
        "mixers": [
            ("M1", "Head Down Inface Circles"),
            ("M2", "Head Up Inface Circles"),
            ("M3", "Mixed Circles"),
            ("M4", "Reverse Mixed Circles"),
            ("M5", "Head Down Shuffler"),
            ("M6", "Head Up Shuffler"),
            ("M7", "Mixed Shuffler"),
            ("M8", "Head Down Inface Shuffler"),
            ("M9", "Head Up Inface Shuffler"),
        ],
    },
    "DS": {
        "title": "DS",
        "snakes": [
            ("S-1", "Head-down Inface Snake"),
            ("S-2", "Head-down Switching Snake"),
            ("S-3", "Head-up Inface Snake"),
            ("S-4", "Head-up Switching Snake"),
            ("S-5", "Head-down Mixed Snake"),
            ("S-6", "Head-up Mixed Snake"),
            ("S-7", "Head-down Inface 360 Snake"),
            ("S-8", "Head-up Inface 360 Snake"),
        ],
        "verticals": [
            ("V-1", "Back Layout"),
            ("V-2", "Butterfly"),
            ("V-3", "Classic"),
            ("V-4", "Head-down 360°"),
            ("V-5", "Head-up 360°"),
            ("V-6", "Crossing classic"),
            ("V-7", "Bottom loop"),
        ],
        "mixers": [
            ("M-1", "Head-down Inface Circles"),
            ("M-2", "Head-up Inface Circles"),
            ("M-3", "Mixed Circles"),
            ("M-4", "Reverse Mixed Circles"),
            ("M-5", "Head-down Shuffler"),
            ("M-6", "Head-up Shuffler"),
            ("M-7", "Mixed Shuffler"),
            ("M-8", "Head-down inface Shuffler"),
            ("M-9", "Head-up inface Shuffler"),
        ],
    },
}


def _competition_key() -> str:
    """Return normalized active competition key."""
    if DEFAULT_COMPETITION in COMPETITIONS:
        return DEFAULT_COMPETITION
    return "D2W_D4W"


def _active_competition() -> dict[str, object]:
    """Return active competition dictionary."""
    return COMPETITIONS[_competition_key()]


def get_competition_labels() -> dict[str, str]:
    """Return mapping: competition key -> title."""
    return {key: str(value.get("title", key)) for key, value in COMPETITIONS.items()}


def get_competition_pools(key: str | None = None) -> tuple[list[tuple[str, str]], list[tuple[str, str]], list[tuple[str, str]]]:
    """Return snakes, verticals and mixers for requested competition."""
    selected_key = key if key in COMPETITIONS else _competition_key()
    selected = COMPETITIONS[selected_key]
    snakes = list(selected["snakes"])
    verticals = list(selected["verticals"])
    mixers = list(selected["mixers"])
    return snakes, verticals, mixers


def get_competition_title(key: str | None = None) -> str:
    """Return title for requested competition."""
    selected_key = key if key in COMPETITIONS else _competition_key()
    return str(COMPETITIONS[selected_key]["title"])


# Backward-compatible aliases used across app.
SNAKES, VERTICALS, MIXERS = get_competition_pools()
APP_TITLE_TEXT = get_competition_title()


def _resolve_external_config_path() -> Path:
    """Return external config path in current working directory."""
    return Path.cwd() / "DrawGenerators.cfg"


def _build_default_external_config() -> str:
    """Return text template for autogenerated external config file."""
    return (
        "\"\"\"External runtime config for DrawGeneratorsApp.\n"
        "Auto-generated on first run.\n"
        "Only UPPERCASE variables are applied.\n\"\"\"\n\n"
        f"DEFAULT_COMPETITION = {DEFAULT_COMPETITION!r}\n\n"
        f"ANIMATION_STEP_DELAY_MS = {ANIMATION_STEP_DELAY_MS!r}\n"
        f"ANIMATION_STEP_COUNT = {ANIMATION_STEP_COUNT!r}\n\n"
        f"ANIMATION_PREVIEW_ROUNDS = {ANIMATION_PREVIEW_ROUNDS!r}\n\n"
        f"COMPETITIONS = {pformat(COMPETITIONS, width=100)}\n"
    )


def save_competition_title(competition_key: str, title: str) -> bool:
    """Persist one competition title to external config file."""
    if competition_key not in COMPETITIONS:
        return False

    normalized = title.strip()

    COMPETITIONS[competition_key]["title"] = normalized
    globals()["APP_TITLE_TEXT"] = get_competition_title()

    external_path = _resolve_external_config_path()
    _ensure_external_config_exists(external_path)
    try:
        external_path.write_text(_build_default_external_config(), encoding="utf-8")
    except OSError:
        return False
    return True


def _ensure_external_config_exists(path: Path) -> None:
    """Create config file with default values if it does not exist."""
    if path.exists():
        return
    try:
        path.write_text(_build_default_external_config(), encoding="utf-8")
    except OSError:
        # App should still run with bundled defaults if write is not allowed.
        return


def _apply_external_overrides() -> None:
    """Load external config and override uppercase values when file exists."""
    external_path = _resolve_external_config_path()
    _ensure_external_config_exists(external_path)

    if not external_path.exists():
        return

    try:
        values = runpy.run_path(str(external_path))
    except Exception:
        # Keep app runnable even if user-supplied config has errors.
        return

    for key, value in values.items():
        if key.isupper():
            globals()[key] = value


_apply_external_overrides()

# Backward compatibility: if external config uses legacy flat pools,
# map them into D2W_D4W competition.
if isinstance(globals().get("SNAKES"), list) and isinstance(globals().get("VERTICALS"), list) and isinstance(globals().get("MIXERS"), list):
    if "D2W_D4W" not in COMPETITIONS:
        COMPETITIONS["D2W_D4W"] = {"title": "D2W & D4W", "snakes": [], "verticals": [], "mixers": []}
    COMPETITIONS["D2W_D4W"]["snakes"] = list(globals()["SNAKES"])
    COMPETITIONS["D2W_D4W"]["verticals"] = list(globals()["VERTICALS"])
    COMPETITIONS["D2W_D4W"]["mixers"] = list(globals()["MIXERS"])

SNAKES, VERTICALS, MIXERS = get_competition_pools()
APP_TITLE_TEXT = get_competition_title()

