"""Configuration with all available dive pool elements.

Supports external override file:
- file name: `DrawGenerators.cfg`
- location: current working directory
- created automatically with defaults when missing
- only uppercase variables override bundled defaults
"""

from __future__ import annotations

import runpy
from pathlib import Path
from pprint import pformat

# UI text configuration.
APP_TITLE_TEXT = "D2W & D4W"

# Shuffle animation configuration.
ANIMATION_STEP_DELAY_MS = 300
ANIMATION_STEP_COUNT = 12


SNAKES = [
    ("S1", "Head-down Inface Snake"),
    ("S2", "Head-down Switching Snake"),
    ("S3", "Head-up Inface Snake"),
    ("S4", "Head-up Switching Snake"),
    ("S5", "Head-down Mixed Snake"),
    ("S6", "Head-up Mixed Snake"),
]

VERTICALS = [
    ("V1", "Back Layout"),
    ("V2", "Butterfly"),
    ("V3", "Classic"),
    ("V4", "Head-down 360°"),
    ("V5", "Head-up 360°"),
    ("V6", "Crossing Classic"),
    ("V7", "Bottom Loop"),
    ("V8", "Crossing Layout"),
]

MIXERS = [
    ("M1", "Head Down Inface Circles"),
    ("M2", "Head Up Inface Circles"),
    ("M3", "Mixed Circles"),
    ("M4", "Reverse Mixed Circles"),
    ("M5", "Head Down Shuffler"),
    ("M6", "Head Up Shuffler"),
    ("M7", "Mixed Shuffler"),
    ("M8", "Head Down Inface Shuffler"),
    ("M9", "Head Up Inface Shuffler"),
]


def _resolve_external_config_path() -> Path:
    """Return external config path in current working directory."""
    return Path.cwd() / "DrawGenerators.cfg"


def _build_default_external_config() -> str:
    """Return text template for autogenerated external config file."""
    return (
        "\"\"\"External runtime config for DrawGeneratorsApp.\n"
        "Auto-generated on first run.\n"
        "Only UPPERCASE variables are applied.\n\"\"\"\n\n"
        f"APP_TITLE_TEXT = {APP_TITLE_TEXT!r}\n\n"
        f"ANIMATION_STEP_DELAY_MS = {ANIMATION_STEP_DELAY_MS!r}\n"
        f"ANIMATION_STEP_COUNT = {ANIMATION_STEP_COUNT!r}\n\n"
        f"SNAKES = {pformat(SNAKES, width=88)}\n\n"
        f"VERTICALS = {pformat(VERTICALS, width=88)}\n\n"
        f"MIXERS = {pformat(MIXERS, width=88)}\n"
    )


def _ensure_external_config_exists(path: Path) -> None:
    """Create config file with default values if it does not exist."""
    if path.exists():
        return
    try:
        path.write_text(_build_default_external_config(), encoding="utf-8")
    except OSError:
        # App should still run with bundled defaults if write is not allowed.
        return


def _apply_external_overrides() -> None:
    """Load external config and override uppercase values when file exists."""
    external_path = _resolve_external_config_path()
    _ensure_external_config_exists(external_path)

    if not external_path.exists():
        return

    try:
        values = runpy.run_path(str(external_path))
    except Exception:
        # Keep app runnable even if user-supplied config has errors.
        return

    for key, value in values.items():
        if key.isupper():
            globals()[key] = value


_apply_external_overrides()
