"""Configuration for Flyer Generators app.

Supports external override file:
- file name: `FlyerGenerators.cfg`
- location: current working directory
- created automatically with defaults when missing
- only uppercase variables override bundled defaults
"""

from __future__ import annotations

import runpy
from pathlib import Path
from pprint import pformat

APP_TITLE_TEXT = "Flyer Generators"
ANIMATION_STEP_DELAY_MS = 70
ANIMATION_STEP_COUNT = 50
DEFAULT_ROUND_COUNT = 5
MAX_ROUND_COUNT = 10
DEFAULT_TEAM_SIZE = 2
MIN_TEAM_SIZE = 1
MAX_TEAM_SIZE = 4


def _resolve_external_config_path() -> Path:
    """Return external config path in current working directory."""
    return Path.cwd() / "FlyerGenerators.cfg"


def _build_default_external_config() -> str:
    """Return text template for autogenerated external config file."""
    return (
        "\"\"\"External runtime config for FlyerGeneratorsApp.\n"
        "Auto-generated on first run.\n"
        "Only UPPERCASE variables are applied.\n\"\"\"\n\n"
        f"APP_TITLE_TEXT = {APP_TITLE_TEXT!r}\n"
        f"ANIMATION_STEP_DELAY_MS = {ANIMATION_STEP_DELAY_MS!r}\n"
        f"ANIMATION_STEP_COUNT = {ANIMATION_STEP_COUNT!r}\n"
        f"DEFAULT_ROUND_COUNT = {DEFAULT_ROUND_COUNT!r}\n"
        f"MAX_ROUND_COUNT = {MAX_ROUND_COUNT!r}\n"
        f"DEFAULT_TEAM_SIZE = {DEFAULT_TEAM_SIZE!r}\n"
        f"MIN_TEAM_SIZE = {MIN_TEAM_SIZE!r}\n"
        f"MAX_TEAM_SIZE = {MAX_TEAM_SIZE!r}\n"
    )


def _ensure_external_config_exists(path: Path) -> None:
    if path.exists():
        return
    try:
        path.write_text(_build_default_external_config(), encoding="utf-8")
    except OSError:
        return


def _apply_external_overrides() -> None:
    external_path = _resolve_external_config_path()
    _ensure_external_config_exists(external_path)
    if not external_path.exists():
        return
    try:
        values = runpy.run_path(str(external_path))
    except Exception:
        return

    for key, value in values.items():
        if key.isupper():
            globals()[key] = value


_apply_external_overrides()
